name: LSIF
on:
  - push
jobs:
  lsif-go:
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-go
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Generate LSIF data
        run: lsif-go
      - name: Upload LSIF data
        run: src lsif upload -github-token=${{ secrets.GITHUB_TOKEN }}
