name: scip-go
"on":
  push:
    branches: [master]
    paths:
      - '**.go'
      - '**/scip-go.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  scip-go:
    if: github.repository_owner == 'sourcegraph'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Run scip-go and upload
        uses: sourcegraph/scip-go-action@v2
        with:
          sourcegraph-url: https://sourcegraph.sourcegraph.com/
          sourcegraph-token: ${{ secrets.SRC_ACCESS_TOKEN_S2 }}
          upload: true
